In [15]:
import numpy as np 
import pandas as pd

In [16]:
dict1 = {
    "name":['harry', 'rohan', 'skillf', 'shubh'],
    "marks":[92,34,24,17],
    "city":['rampur', 'kolkata', 'bareilly', 'antarctica']
}

In [17]:
df = pd.DataFrame(dict1)

In [ ]:
df

In [19]:
df.to_csv('friends.csv')

In [20]:
df.to_csv('friends_index_false.csv', index=False)

In [23]:
df.head(2)

    name  marks     city
0  harry     92   rampur
1  rohan     34  kolkata

In [24]:
df.tail(2)

     name  marks        city
2  skillf     24    bareilly
3   shubh     17  antarctica