In [ ]:
import pandas as pd  

csv_1 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv")

csv_1

   Unnamed: 0  a  s  d
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5
5           5  6  6  6

In [45]:
# csv_2 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",nrows=1)

# csv_2 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",usecols=["a","s"])

csv_2 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",usecols=[0,2])

csv_2

# print(type(csv_2))

   Unnamed: 0  s
0           0  1
1           1  2
2           2  3
3           3  4
4           4  5
5           5  6

In [46]:
csv_3 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",skiprows=[0,3])

csv_3

   0  1  1.1  1.2
0  1  2    2    2
1  3  4    4    4
2  4  5    5    5
3  5  6    6    6

In [47]:
csv_4 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",index_col="a")

csv_4

   Unnamed: 0  s  d
a
1           0  1  1
2           1  2  2
3           2  3  3
4           3  4  4
5           4  5  5
6           5  6  6

In [48]:
csv_5 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",header=[2])

csv_5

   1  2  2.1  2.2
0  2  3    3    3
1  3  4    4    4
2  4  5    5    5
3  5  6    6    6

In [49]:
csv_6 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",names=["col1","col2","col3","col4"])

csv_6

   col1 col2 col3 col4
0   NaN    a    s    d
1   0.0    1    1    1
2   1.0    2    2    2
3   2.0    3    3    3
4   3.0    4    4    4
5   4.0    5    5    5
6   5.0    6    6    6

In [ ]:
csv_1 = pd.read_csv("C:\\Users\\param\\OneDrive\\Desktop\\pandas\\Test_new.csv",header = None, prefix = "col",dtype={"a":"float"})

csv_1